project:
  type: website

website:
  title: "IQB Methods Team"
  site-url: https://iqb-research.github.io/R-SIG/
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/nickhaf/r_tutorial
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
    right:
      - icon: rss
      - href: index.xml

  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "Workshops"
        contents:
          - docs/workshops/workshops.qmd
      - section: "Additional material"
        contents: 
          - docs/material/material.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

