project:
  type: website

website:
  title: "IQB Methods Team"
  site-url: https://iqb-research.github.io/IQB-Methods/
  page-navigation: true
  open-graph: true
  repo-url: https://github.com/IQB-Methods
  repo-actions: [edit, issue]
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: posts_r_sig.qmd
        text: R-Sig
      - href: posts_newsletter.qmd
        text: Newsletter
    right:
      - icon: rss
      - href: index.xml

  sidebar: 
    style: "docked"
    search: true
    contents:
      - section: "Additional Material"
        contents:
          - docs/workshops/workshops.qmd
          - docs/material/material.qmd
          - docs/tutorials/tutorials.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

